#include QMK_KEYBOARD_H

#ifdef COMBO_ENABLE
#   include "combos.h"
#endif


#define _LAYER0 0
#define _LAYER1 1
#define _LAYER2 2
#define _LAYER3 3
#define _LAYER4 4
#define _LAYER5 5

enum layers {
    LAYER0 = 0,
    LAYER1,
    LAYER2,
    LAYER3,
    LAYER4,
    LAYER5,
};

 const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

 [_alp] = LAYOUT(KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_CAPS, KC_A, KC_R, KC_S, KC_T, KC_G, KC_M, KC_N, KC_E, KC_I, KC_O, LSFT_T(KC_Z), LCTL_T(KC_X), KC_C, KC_D, KC_V, KC_K, KC_H, KC_COMM, LCTL_T(KC_DOT), LSFT_T(KC_TAB), LALT(KC_NO), OSL(2), LT(1,KC_SPC), KC_BSPC, LT(3,KC_ENT), KC_NO),

[_LAYER1] = LAYOUT(KC_1, KC_MUTE, KC_VOLD, KC_VOLU, KC_5, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_PSCR, OSM(MOD_LSFT), OSM(MOD_LCTL), OSM(MOD_LALT), OSM(MOD_LGUI), KC_ESC, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_H, LSFT_T(KC_6), LALT_T(KC_7), LCTL_T(KC_8), KC_NO, KC_0, KC_K, KC_M, LCTL_T(KC_NO), LALT_T(KC_NO), RSFT_T(KC_SCLN), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_DEL, KC_TRNS),

[_LAYER2] = LAYOUT(KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_LT, KC_LBRC, KC_EQL, KC_RBRC, KC_GT, KC_QUES, KC_QUOT, KC_DQUO, KC_SCLN, KC_TILD, KC_LCBR, KC_LPRN, KC_COLN, KC_RPRN, KC_RCBR, KC_NUHS, KC_CIRC, KC_PIPE, KC_AMPR, KC_GRV, KC_SLSH, KC_UNDS, KC_MINS, KC_PLUS, KC_ASTR, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

[_LAYER3] = LAYOUT(KC_MPRV, KC_MUTE, KC_VOLD, KC_VOLU, KC_MNXT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

[_LAYER4] = LAYOUT(KC_NO, KC_F9, KC_F10, KC_F11, KC_F12, KC_PPLS, KC_P7, KC_P8, KC_P9, KC_PSLS, KC_NO, KC_F5, KC_F6, KC_F7, KC_F8, KC_P0, KC_P4, KC_P5, KC_P6, KC_PDOT, KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_PMNS, KC_P1, KC_P2, KC_P3, KC_PAST, KC_NO, KC_NO, KC_NO, KC_PEQL, KC_PENT, KC_NO),


};